name:                Jsonr
version:             0.1.0.0
github:              "FloatingLion/Jsonr"
license:             MIT
author:              "Lifoz"
maintainer:          "floatinglion@outlook.com"
copyright:           "2021 Lifoz"

extra-source-files:
- README.org
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: 一个对JSON的解析、处理系统

dependencies:
- base >= 4.7 && < 5
- mtl >= 2
- directory >= 1
- filepath
- hspec >= 2.7
- lens
- optparse-applicative
- containers

library:
  source-dirs: src

executables:
  Jsonr-trans:
    main:                Main.hs
    source-dirs:         app/Jsonr-trans
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Jsonr

tests:
  Jsonr-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Jsonr
